name: Build a Publish

on:
    release:
        types:
            - published
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Install build dependencies
              run: pip install -r build-requirements.txt

            - name: Run build script
              run: python -m build.py

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
                  package: dist/*

            - name: Publish to GitHub
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/*
