name: Build and Publish

on:
    release:
        types:
            - published

permissions:
    contents: write
    id-token: write

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Install build dependencies
              run: pip install -r build-requirements.txt

            - name: Get version from GitHub tag
              id: get_version
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Update version in version.py
              run: |
                  echo "__version__ = \"$VERSION\"" > generate_gitignore/version.py

            - name: Commit and push version update
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "noreply@github.com"
                  git add generate_gitignore/version.py
                  git commit -m "Update version.py to $VERSION"
                  git push origin ${{ github.ref_name }}

            - name: Ensure version update on main branch
              run: |
                  git fetch origin main
                  git checkout main
                  git pull origin main
                  git merge ${{ github.ref_name }} --no-ff -m "Merge release branch to main with version update"
                  git push origin main

            - name: Build the package
              run: python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1

            - name: Upload to Release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*
